name: Generate PDF index

on:
  push:
    paths:
      - 'pdfs/**.pdf'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate index.html for each folder
        run: |
          for dir in pdfs/*/; do
            year=$(basename "$dir")
            echo "<!DOCTYPE html>" > "$dir/index.html"
            echo "<html lang='ar' dir='rtl'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1'><title>$year - الواجبات البيتية</title></head><body>" >> "$dir/index.html"
            echo "<h1>الواجبات البيتية $year</h1><ul>" >> "$dir/index.html"
            for pdf in "$dir"*.pdf; do
              file=$(basename "$pdf")
              echo "<li><a href='$file' target='_blank'>$file</a></li>" >> "$dir/index.html"
            done
            echo "</ul><p><a href='../index.html'>العودة</a></p></body></html>" >> "$dir/index.html"
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pdfs/*/index.html
          git commit -m "Auto-generate PDF indexes" || echo "No changes"
          git push
